<template>
    <!-- for web -->
    <section class="hidden lg:block h-[682px] bg-[#F6F8FF]">
        <div class="grid grid-cols-2 h-full">
            <div class="flex items-center justify-end ">
                <div class="w-[685px]">
                    <div class="">
                        <p class="text-[36px] font-[700]">Sales Order</p>
                        <p>A sales order is a document generated by the seller specifying the details about the product or
                            services ordered by the customer. Along with the product and service details, sales order
                            consists of price, quantity, terms, and conditions etc.</p>
                    </div>
                    <div class="pt-10">
                        <div class="grid grid-cols-1">
                            <div class="">
                                <div class="flex items-center">
                                    <img src="~/assets/img/soicon.png" alt="">
                                    <p class="text-[24px] font-[700] ps-4">Sales Analysis</p>
                                </div>
                                <p class="ps-16">Schedule Appointment, Estimate, Inspection & Health card, Job Card,
                                    Invoice, Order Summary.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="flex items-center justify-center">
                <img src="~/assets/img/soimage.png" alt="">
            </div>
        </div>
    </section>
    <!-- for phone -->
    <section class=" h-[700px] lg:hidden bg-[#F6F8FF]">
        <div class="pt-12">
            <div class="flex justify-center">
                <div class="w-[343px]">
                    <p class="text-[24px] font-[700] text-center">Sales Order</p>
                    <p class="text-center">A sales order is a document generated by the seller specifying the details about
                        the product or
                        services ordered by the customer. Along with the product and service details, sales order
                        consists of price, quantity, terms, and conditions etc.</p>

                </div>
            </div>
            <div class="flex justify-center pt-8">
                <img src="~/assets/img/soimagemobile.png" alt="">
            </div>
            <div>
                <div class="grid grid-cols-1 p-6 pt-10">
                    <div class="">
                        <div class="flex items-center">
                            <img class="w-[40px]" src="~/assets/img/soicon.png" alt="">
                            <p class="text-[20px] font-[700] ps-4">Sales Analysis</p>
                        </div>
                        <p class="ps-16">Schedule Appointment, Estimate, Inspection & Health card, Job Card,
                            Invoice, Order Summary.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>