<script setup>
import SalesComponent from "./salesComponent.vue";
import Icon1 from "../../../../assets/img/Sales/Group 1000010388.svg"
import Icon2 from "../../../../assets/img/Sales/Group 1000010388 (1).svg"
import Image2 from "../../../../assets/img/soimage.png"
import Image3 from "../../../../assets/img/soimagemobile.png"

const mobileClass = "lg:hidden bg-blue-3 md:px-[3rem] px-[1rem] py-[3rem]";
const webClass = "hidden lg:block bg-blue-3 3xl:px-[16.25rem] 3xl:py-[7.5rem] lg:px-[3rem] xl:px-[10rem] lg:py-[4rem]"

    // For web
    const webProps = {
      title: 'Sales Order',
      description: 'A sales order is a document generated by the seller specifying the details about the product or services ordered by the customer. Along with the product and service details, sales order consists of price, quantity, terms, and conditions etc.',
      salesAnalysis: {
        title: 'Sales Analysis',
        icon: Icon1,
        description: 'Schedule Appointment, Estimate, Inspection & Health card, Job Card, Invoice, Order Summary.',
      },
      image: Image2,
      sectionClasses: webClass ,
    };

    // For phone
    const phoneProps = {
      title: 'Sales Order',
      description: 'A sales order is a document generated by the seller specifying the details about the product or services ordered by the customer. Along with the product and service details, sales order consists of price, quantity, terms, and conditions etc.',
      salesAnalysis: {
        title: 'Sales Analysis',
        icon: Icon2,
        description: 'Schedule Appointment, Estimate, Inspection & Health card, Job Card, Invoice, Order Summary.',
      },
      image: Image3,
      sectionClasses: mobileClass,
    };
</script>
<template>
  <div>
    <!-- For web -->
    <SalesComponent
        :title="webProps.title"
        :description="webProps.description"
        :salesAnalysis="webProps.salesAnalysis"
        :image="webProps.image"
        :sectionClasses="webProps.sectionClasses"
    />

    <!-- For phone -->
    <SalesComponent
        :title="phoneProps.title"
        :description="phoneProps.description"
        :salesAnalysis="phoneProps.salesAnalysis"
        :image="phoneProps.image"
        :sectionClasses="phoneProps.sectionClasses"
    />
  </div>
</template>